server:
  port: 8081

spring:
  application :
    name : auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: postgres

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
