server:
  port: 8082

spring:
  application :
    name : chat-service

  datasource:
    url: jdbc:postgresql://localhost:5432/chatdb
    username: postgres
    password: postgres

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
