server:
  port : 8082
spring:
  application :
    name : chat-service

  config:
    import: optional:configserver:http://localhost:8888
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org:
      springframework:
        cloud: 
          config: DEBUG
#test: