server:
  port: 8084

spring:
  application :
    name : file-service

  datasource:
    url: jdbc:postgresql://localhost:5432/filedb
    username: postgres
    password: postgres

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
