server:
  port: 8085

spring:
  # L'application name peut être dans application.yml ou bootstrap.yml.
  # Le maintenir ici est acceptable, mais la bonne pratique pour l'utilisation du Config Server est de le mettre dans bootstrap.yml également.
  application:
    name: organisations-service

  # --- SECTION SUPPRIMÉE/CORRIGÉE ---
  # La section 'cloud: config: import:' doit être supprimée de application.yml.
  # Elle doit être déplacée dans 'bootstrap.yml'.

  datasource:
    url: jdbc:postgresql://localhost:5432/Uniworkorganisations2
    username: postgres
    password: 123
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,circuitbreakers,retries,metrics
  endpoint:
    health:
      show-details: always

# Configuration Resilience4j
resilience4j:
  circuitbreaker:
    instances:
      userServiceCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

  retry:
    instances:
      userServiceRetry:
        maxAttempts: 3
        waitDuration: 1000
        retryExceptions:
          - java.io.IOException
          - java.net.ConnectException