server:
  port: 8085

spring:
  application:
    name: organisations-service

  datasource:
    url: jdbc:postgresql://localhost:5432/Uniworkorganisations2
    username: postgres
    password: 123
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
logging:
  level:
    com.moustakim.organisationsservice.feign: DEBUG
    feign: DEBUG
    
management:
  endpoints:
    web:
      exposure:
        include: health,circuitbreakers,retries,metrics
  endpoint:
    health:
      show-details: always

# Configuration Resilience4j
resilience4j:
  circuitbreaker:
    instances:
      authServiceCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

  retry:
    instances:
      authServiceRetry:
        maxAttempts: 3
        waitDuration: 1000
        retryExceptions:
          - java.io.IOException
          - java.net.ConnectException